### ISSUE TITLE
Documentations for installation

### ISSUE THREAD

**Issue by salaithianlianben** [Ar-Ray-code/YOLOX-ROS#41]
**Could you please provide us steps of installation?**

**Comment by Ar-Ray-code** [comment]
Was the following documentation not sufficient?

https://github.com/Ar-Ray-code/YOLOX-ROS/blob/humble/yolox_ros_cpp/README.md

The install method depends on your computing environment and the launch file you want to exec, so unless you tell me, I cannot support it ☹️

**Comment by juni3227** [comment]
The documentation does not explain about dependency. I am facing multiple issues with dependency that is not explained in the documentation, such as _generate_parameter_library_ and more. 

I tried to solve that with rosdep, then turns out I have to install CV2 c++ first.

I am using fresh install of ros2 jazzy, if you are wondering.  I do not feel this is right. I can not get this thing build with just documentation.

**Comment by juni3227** [comment]
I found out that, installing dependency using
`apt install -y ros-dev-tools \
                    ros-jazzy-cv-bridge \
                    ros-jazzy-generate-parameter-library \
                    ros-jazzy-parameter-traits \
                    ros-jazzy-ros-base \
                    ros-jazzy-rqt-image-view \
                    ros-jazzy-usb-cam \
                    ros-jazzy-vision-msgs && \`
from your docker file. And it built with errors. 

If your apt can not find these packages, look ROS2 documentation for installation. You may have not added your ros2 remote repositories.
